#!/bin/bash
SCRIPT_ABS_FILENAME=`LC_ALL=en_US.ISO8859-1 perl -e 'use Cwd "abs_path";print abs_path(shift)' "${BASH_SOURCE[0]}"`
SCRIPT_DIR=`dirname "$SCRIPT_ABS_FILENAME"`

cd "$SCRIPT_DIR"

path=$1

set -x


dir=mnt_fuse
if [ -d mnt_fuse/root ]
then
  dir=mnt_fuse/root
fi

if ! [ -f "$dir"/SmallFile0 ]
then
  echo SmallFile0 doesn\'t exist in "$path"
  exit 1
fi

rsync_cmd=(/JiefLand/5.Devel/RsyncJief/rsync-v3.1.3/rsync-3.1.3-crtimes-osx-xcode/XcodeProj/DerivedData/rsync-v3.1.3/Build/Products/Debug/rsync-v3.1.3 \
  -azHX --crtimes \
  --out-format='%i  - %n  - %M' \
  -n \
  "$dir"/ mnt_hdiutil/)

"${rsync_cmd[@]}"
if ! [ $? -eq 0 ]
then
  echo rsync return error "$path"
  exit 1
fi

nblines=$("${rsync_cmd[@]}" | wc -l)

if [ $nblines -eq 0 ]
then
  echo '------------------------------------------------------------->' Test OK
  ret=0
else
  echo '------------------------------------------------------------->' Test failed
  ret=1
fi

exit $ret
